src/main/java/com/capstone/foodpanda/model/Cart.java
package com.capstone.foodpanda.model;

import javax.persistence.*;
import java.io.Serializable;

@Entity
@Table(name = "cart")
public class Cart implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private int id;

    // creating one to one relationship

    @OneToOne
    private User user;

    @Column(name = "grand_total")
    private double grandTotal;

    @Column(name = "cart_lines")
    private int cartLines;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public double getGrandTotal() {
        return grandTotal;
    }

    public void setGrandTotal(double grandTotal) {
        this.grandTotal = grandTotal;
    }

    public int getCartLines() {
        return cartLines;
    }

    public void setCartLines(int cartLines) {
        this.cartLines = cartLines;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Override
    public String toString() {
        return "Cart [id=" + id + ", grandTotal=" + grandTotal + ", cartLines=" + cartLines + "]";
    }


}

src/main/java/com/capstone/foodpanda/model/CartLine.java
package com.capstone.foodpanda.model;

import javax.persistence.*;
import java.io.Serializable;

@Entity
@Table(name = "cart_line")
public class CartLine implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private int id;

    @OneToOne
    private Product product;

    @Column(name = "cart_id")
    private int cartId;

    @Column(name = "total")
    private double total;

    @Column(name = "product_count")
    private int productCount;

    @Column(name = "buying_price")
    private double buyingPrice;

    @Column(name = "is_available")
    private boolean isAvailable;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getCartId() {
        return cartId;
    }

    public void setCartId(int cartId) {
        this.cartId = cartId;
    }

    public double getTotal() {
        return total;
    }

    public void setTotal(double total) {
        this.total = total;
    }

    public int getProductCount() {
        return productCount;
    }

    public void setProductCount(int productCount) {
        this.productCount = productCount;
    }

    public double getBuyingPrice() {
        return buyingPrice;
    }

    public void setBuyingPrice(double buyingPrice) {
        this.buyingPrice = buyingPrice;
    }

    public boolean isAvailable() {
        return isAvailable;
    }

    public void setAvailable(boolean isAvailable) {
        this.isAvailable = isAvailable;
    }


    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    @Override
    public String toString() {
        return "CartLine [id=" + id + ", cartId=" + cartId + ", total=" + total + ", productCount=" + productCount
                + ", buyingPrice=" + buyingPrice + ", isAvailable=" + isAvailable + "]";
    }


}

src/main/java/com/capstone/foodpanda/controllers/CartController.java
package com.capstone.foodpanda.controllers;

import com.capstone.foodpanda.model.Cart;
import com.capstone.foodpanda.model.CartLine;
import com.capstone.foodpanda.model.Product;
import com.capstone.foodpanda.service.CartLineService;
import com.capstone.foodpanda.service.CartService;
import com.capstone.foodpanda.service.ProductService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

@Controller
@RequestMapping("/cart")
public class CartController {

    @Autowired
    @Qualifier("cartLineService")
    private CartLineService cartLineService;

    @Autowired
    @Qualifier("productService")
    private ProductService productService;

    @Autowired
    @Qualifier("cartService")
    private CartService cartService;

    @GetMapping("/show")
    public ModelAndView showCart(@RequestParam(name = "result", required = false) String result) {
        ModelAndView modelAndView = new ModelAndView("page");

        if (result != null) {
            switch (result) {
                case "updated":
                    modelAndView.addObject("message", "CartLine has been updated sucessfully");
                    break;

                case "error":
                    modelAndView.addObject("message", "Something went wrong!!");
                    break;

                case "added":
                    modelAndView.addObject("message", "Cartline has been added sucessfully!");
                    break;

                case "deleted":
                    modelAndView.addObject("message", "Cart has been removed sucessfully");
                    break;
                default:
                    break;
            }
        }

        modelAndView.addObject("title", "User Cart");
        modelAndView.addObject("userClickShowCart", true);
        modelAndView.addObject("cartLines", cartLineService.findCartLines());
        return modelAndView;
    }

    @GetMapping("/{id}/update")
    public String updateCart(@PathVariable int id, @RequestParam int count) {
        CartLine cartLine = cartLineService.findCartLineById(id);
        if (cartLine != null) {
            Product product = cartLine.getProduct();
            double oldTotal = cartLine.getTotal();
            if (product.getQuantity() <= count) {
                count = product.getQuantity();
            }
            cartLine.setProductCount(count);
            cartLine.setBuyingPrice(product.getUnitPrice());
            cartLine.setTotal(product.getUnitPrice() * count);
            String response = cartLineService.updateCartLine(cartLine) + "";
            Cart cart = cartService.findCart();
            cart.setGrandTotal(cart.getGrandTotal() - oldTotal + cartLine.getTotal());
            cartService.updateCart(cart);
            return "redirect:/cart/show?result=updated";
        } else {
            return "redirect:/cart/show?result=error";
        }
    }

    @GetMapping("/{id}/delete")
    public String deleteCart(@PathVariable int id) {
        // TODO : fetch the cartLine
        CartLine cartLine = cartLineService.findCartLineById(id);
        if (cartLine != null) {
            Cart cart = cartService.findCart();
            cart.setGrandTotal(cart.getGrandTotal() - cartLine.getTotal());
            cart.setCartLines(cart.getCartLines() - 1);
            cartService.updateCart(cart);
            // TODO : remove the cartLine
            cartLineService.deleteCartLine(cartLine);
            return "redirect:/cart/show?result=deleted";
        } else {
            return "redirect:/cart/show?result=error";
        }
    }

    @GetMapping("/add/{id}/product")
    public String addCart(@PathVariable int id) {
        // TODO : fetch the cart
        Cart cart = cartService.findCart();
        CartLine cartLine = cartLineService.findCartLineByCartIdAndProductId(cart.getId(), id);
        if (cartLine != null) {

			/*cart.setGrandTotal(cart.getGrandTotal() - cartLine.getTotal());
			cart.setCartLines(cart.getCartLines() - 1);
			cartService.updateCart(cart);
			// TODO : remove the cartLine
			cartLineService.deleteCartLine(cartLine);
			return "redirect:/cart/show?result=deleted";*/
            return "";
        } else {
            cartLine = new CartLine();

            Product product = productService.findProductById(id);
            cartLine.setCartId(cart.getId());
            cartLine.setProduct(product);
            cartLine.setBuyingPrice(product.getUnitPrice());
            cartLine.setProductCount(1);
            cartLine.setTotal(product.getUnitPrice());
            cartLine.setAvailable(true);
            cartLineService.saveCartLine(cartLine);
            cart.setCartLines(cart.getCartLines() + 1);
            cart.setGrandTotal(cart.getGrandTotal() + cartLine.getTotal());
            cartService.saveCart(cart);
            return "redirect:/cart/show?result=added";
        }
    }

}

src/main/webapp/WEB-INF/views/404.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8" %>
<%@taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>


<c:set var="contextRoot" value="${pageContext.request.contextPath }"/>
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Food Panda - ${title }</title>
    <script type="text/javascript">
        window.menu = '${title }';
        window.contextRoot = '${contextRoot}'
    </script>
    <!-- Bootstrap core CSS -->

    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Bootstrap Readable Theme -->
    <link href="/css/bootstrap-readable-theme.css" rel="stylesheet">


    <!-- Bootstrap DataTables -->
    <link href="/css/dataTables.bootstrap.css" rel="stylesheet">


    <!-- Custom CSS -->
    <link href="/css/myapp.css" rel="stylesheet">

</head>

<body>


<div class="wrapper">

    <!-- Navigation -->

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">

                <a class="navbar-brand" href="/home">Home</a>
            </div>
        </div>
    </nav>


    <!-- Page Content -->
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="jumbotron">
                        <h1>${errorTitle }</h1>
                        <hr/>
                        <blockquote>${errorDescription }</blockquote>
                    </div>
                </div>
            </div>

        </div>

    </div>

    <!-- /.container -->

    <!-- Footer -->
    <%@include file="share/footer.jsp" %>
</div>
</body>

</html>

src/main/webapp/WEB-INF/views/about.jsp
<div class="container">

    <div class="row">

        <h1>About Us</h1>
        <hr/>
        <p>This is an about us page</p>

    </div>


</div>

src/main/webapp/WEB-INF/views/cart.jsp
<div class="container">

    <c:if test="${not empty message }">
        <div class="alert alert-info">
            <h3 class="text-center">${message }</h3>
        </div>
    </c:if>

    <c:choose>
        <c:when test="${not empty cartLines }">
            <table id="cart" class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th style="width: 50%">Product</th>
                    <th style="width: 10%">Price</th>
                    <th style="width: 8%">Quantity</th>
                    <th style="width: 22%" class="text-center">Subtotal</th>
                    <th style="width: 10%"></th>
                </tr>
                </thead>


                <tbody>
                <c:forEach items="${cartLines }" var="cartLine">

                    <tr>
                        <td data-th="Product">
                            <div class="row">
                                <div class="col-sm-2 hidden-xs">
                                    <img
                                            src="${rootContext }/static/images/${cartLine.product.code}.jpg"
                                            alt="${cartLine.product.name }"
                                            class="img-responsive cartImg"/>
                                </div>
                                <div class="col-sm-10">
                                    <h4 class="nomargin">${cartLine.product.name }
                                        <c:if test="${cartLine.available == false }">
                                            <strong class="unavailable">(Not Available)</strong>
                                        </c:if>

                                    </h4>
                                    <p>Brand - ${cartLine.product.brand }</p>
                                    <p>Description - ${cartLine.product.description }</p>
                                </div>
                            </div>
                        </td>
                        <td data-th="Price">&#8377; ${cartLine.buyingPrice }</td>
                        <td data-th="Quantity"><input type="number"
                                                      class="form-control text-center" id="count_${cartLine.id }"
                                                      min="1" max="3" value="${cartLine.productCount }"></td>
                        <td data-th="Subtotal" class="text-center">&#8377;
                                ${cartLine.total }</td>
                        <td class="actions" data-th="">
                            <button type="button" name="refreshCart" value="${cartLine.id }"
                                    class="btn btn-info btn-sm">
                                <span class="glyphicon glyphicon-refresh"></span>
                            </button>
                            <a href="${contextRoot }/cart/${cartLine.id}/delete" class="btn btn-danger btn-sm">
                                <span class="glyphicon glyphicon-trash"></span>
                            </a>
                        </td>
                    </tr>

                </c:forEach>


                </tbody>


                <tfoot>
                <tr class="visible-xs">
                    <td class="text-center"><strong>Total &#8377;
                            ${userModel.cart.grandTotal }</strong></td>
                </tr>
                <tr>
                    <td><a href="${contextRoot }/show/all/products" class="btn btn-warning"><span
                            class="glyphicon glyphicon-chevron-left"></span> Continue
                        Shopping</a></td>
                    <td colspan="2" class="hidden-xs"></td>
                    <td class="hidden-xs text-center"><strong>Total
                        &#8377; ${userModel.cart.grandTotal }</strong></td>
                    <td><a href="#" class="btn btn-success btn-block">Checkout
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </a></td>
                </tr>
                </tfoot>

            </table>
        </c:when>
        <c:otherwise>
            <div class="jumbotron">
                <div class="text-center">
                    <h1>Your cart is empty!</h1>

                </div>

            </div>
        </c:otherwise>

    </c:choose>


</div>

src/main/webapp/WEB-INF/views/contact.jsp
<div class="container">

    <div class="row">

        <h1>Contact Us</h1>
        <hr/>
        <p>This is an contact us page</p>

    </div>


</div>

src/main/webapp/WEB-INF/views/home.jsp
<div class="container">

    <div class="row">

        <div class="col-md-3">
            <%@include file="./share/sidebar.jsp" %>
        </div>

        <div class="col-md-9">

            <div class="row carousel-holder">

                <div class="col-md-12">
                    <div id="carousel-example-generic" class="carousel slide"
                         data-ride="carousel">
                        <ol class="carousel-indicators">
                            <li data-target="#carousel-example-generic" data-slide-to="0"
                                class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="3"></li>
                        </ol>
                        <div class="carousel-inner">

                            <div class="item active">
                                <img class="slide-image" src="${contextRoot }/static/images/banner1.jpg"
                                     alt="">
                            </div>
                            <div class="item">
                                <img class="slide-image" src="${contextRoot }/static/images/banner2.jpg"
                                     alt="">
                            </div>
                            <div class="item">
                                <img class="slide-image" src="${contextRoot }/static/images/banner3.jpg"
                                     alt="">
                            </div>
                            <div class="item">
                                <img class="slide-image" src="${contextRoot }/static/images/banner4.jpg"
                                     alt="">
                            </div>
                        </div>
                        <a class="left carousel-control" href="#carousel-example-generic"
                           data-slide="prev"> <span
                                class="glyphicon glyphicon-chevron-left"></span>
                        </a> <a class="right carousel-control"
                                href="#carousel-example-generic" data-slide="next"> <span
                            class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                    </div>
                </div>

            </div>

            <div class="row">
                <div class="col-xs-12">
                    <h3>Our Most Viewed Products</h3>
                    <hr/>
                </div>
            </div>

            <div class="row is-table-row">

                <div class="col-sm-4">
                    <div class="thumbnail">
                       <img src="${contextRoot }/static/images/PROC67489CF18.jpg" alt="">
                        <h5>Your Favourite Dish</h5>
                        <hr/>
                        <div class="caption">
                            <h4 class="pull-right">&#8377; </h4>
                            <p></p>
                            <a class="btn btn-primary pull-right">View</a>
                        </div>
                    </div>

                </div>

                <div class="col-sm-4 col-lg-4 col-md-4">
                    <h4>Checkout more products!</h4>
                    <hr/>
                    <a class="btn btn-primary" href="${contextRoot}/show/all/products">More Products</a>
                </div>

            </div>

            <div class="row">
                <div class="col-xs-12">
                    <h3>Our Most Purchased Products</h3>
                    <hr/>
                </div>
            </div>
            <div class="row is-table-row">

                <div class="col-sm-4">
                    <div class="thumbnail">
                        <img alt="Your favourite dish" src="${contextRoot }/static/images/PROF02EB40085.jpg">
                        <h5></h5>
                        <hr/>
                        <div class="caption">
                            <h4 class="pull-right">&#8377; </h4>
                            <p></p>
                            <a class="btn btn-primary pull-right">View</a>
                        </div>
                    </div>
                </div>

                <div class="col-sm-4 col-lg-4 col-md-4">
                    <h4>Checkout more products!</h4>
                    <hr/>
                    <a class="btn btn-primary" href="${contextRoot}/show/all/products">More Products</a>
                </div>

            </div>

        </div>

    </div>

</div>
<!-- /.container -->

src/main/webapp/WEB-INF/views/listProducts.jsp
<div class="container">

    <div class="row">


        <!-- Would be to display sidebar -->
        <div class="col-md-3">
            <%@include file="share/sidebar.jsp" %>

        </div>

        <!-- to display the actual products -->
        <div class="col-md-9">

            <!-- Added breadcrumb component -->
            <div class="row">

                <div class="col-lg-12">
                    <c:if test="${userClickAllProducts == true}">
                        <script>
                            window.categoryId = '';
                        </script>

                        <ol class="breadcrumb">
                            <li><a href="/home">Home</a></li>
                            <li class="active"><span>All Products</span></li>
                        </ol>


                    </c:if>

                    <c:if test="${userClickCategoryProducts == true}">
                        <script>
                            window.categoryId = '${category.id}';
                        </script>
                        <ol class="breadcrumb">
                            <li><a href="/home">Home</a></li>
                            <li class="active"><a href="#">Category</a></li>
                            <li class="active"><span>${category.name }</span></li>

                        </ol>
                    </c:if>
                </div>
            </div>


            <div class="row">

                <div class="col-xs-12">
                    <div class="container-fluid">
                        <div class="table-responsive">


                            <table id="productListTable"
                                   class="table table-striped table-borderd">


                                <thead>
                                <tr>
                                    <th></th>
                                    <th>Name</th>
                                    <th>Brand</th>
                                    <th>Price</th>
                                    <th>Qty. Available</th>
                                    <th></th>
                                </tr>
                                </thead>


                                <tfoot>
                                <tr>
                                    <th></th>
                                    <th>Name</th>
                                    <th>Brand</th>
                                    <th>Price</th>
                                    <th>Qty. Available</th>
                                    <th></th>
                                </tr>
                                </tfoot>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

src/main/webapp/WEB-INF/views/login.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8" %>
<%@taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<c:set var="contextRoot" value="${pageContext.request.contextPath }"/>
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Food Panda - ${title }</title>
    <script type="text/javascript">
        window.menu = '${title }';
        window.contextRoot = '${contextRoot}'
    </script>
    <!-- Bootstrap core CSS -->

    <link href="${contextRoot }/static/css/bootstrap.min.css"
          rel="stylesheet">

    <!-- Bootstrap Readable Theme -->
    <link href="${contextRoot }/static/css/bootstrap-readable-theme.css"
          rel="stylesheet">

    <!-- Custom CSS -->
    <link href="${contextRoot }/static/css/myapp.css" rel="stylesheet">

</head>

<body>


<div class="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="${contextRoot }/home">Online
                    Shopping</a>
            </div>
        </div>
    </nav>

    <!-- Page Content -->
    <div class="content">
        <div class="container">

            <c:if test="${not empty message }">
                <div class="row">
                    <div class="col-md-offset-3 col-md-6">
                        <div class="alert alert-danger">${message }</div>
                    </div>
                </div>

            </c:if>

            <c:if test="${not empty logout }">
                <div class="row">
                    <div class="col-md-offset-3 col-md-6">
                        <div class="alert alert-success">${logout }</div>
                    </div>
                </div>

            </c:if>

            <div class="row">
                <div class="col-md-offset-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h4>Login</h4>
                        </div>
                        <div class="panel-body">
                            <form action="${contextRoot }/login" method="post"
                                  class="form-horizontal" id="loginForm">
                                <div class="form-group">
                                    <label for="username" class="col-md-4 control-label">Email
                                        : </label>
                                    <div class="col-md-8">
                                        <input type="email" name="username" class="form-control"/>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="password" class="col-md-4 control-label">Password
                                        : </label>
                                    <div class="col-md-8">
                                        <input type="password" name="password" class="form-control"/>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-4 col-md-8">
                                        <input type="submit" name="password" class="btn btn-primary"/>
                                        <input type="hidden" name="${_csrf.parameterName }"
                                               value="${_csrf.token }"/>
                                    </div>
                                </div>

                            </form>
                        </div>
                        <div class="panel-footer">
                            <div class="text-right">
                                New User - <a href="${contextRoot }/register">Register Here</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Page Content -->
    <!-- Footer -->
    <%@include file="share/footer.jsp" %>

    <!-- jQuery -->
    <script src="${contextRoot }/static/js/jquery.js"></script>

    <!-- jQuery validator -->
    <script src="${contextRoot }/static/js/jquery.validate.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="${contextRoot }/static/js/bootstrap.min.js"></script>

    <!-- Self coded javascript -->
    <script src="${contextRoot }/static/js/myapp.js"></script>
</div>
</body>

</html>

src/main/webapp/WEB-INF/views/page.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8" %>
<%@taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<c:set var="contextRoot" value="${pageContext.request.contextPath }"/>
<!DOCTYPE html>
<html lang="en">

<head>

    <meta name="_csrf" content="${_csrf.token }">
    <meta name="_csrf_header" content="${_csrf.headerName }">


    <title>Food Panda - ${title }</title>
    <script type="text/javascript">
        window.menu = '${title }';
        window.contextRoot = '${contextRoot}'
    </script>
    <!-- Bootstrap core CSS -->

    <link href="${contextRoot }/static/css/bootstrap.min.css"
          rel="stylesheet">

    <!-- Bootstrap Readable Theme -->
    <link href="${contextRoot }/static/css/bootstrap-readable-theme.css"
          rel="stylesheet">


    <!-- Bootstrap DataTables -->
    <link href="${contextRoot }/static/css/dataTables.bootstrap.css"
          rel="stylesheet">


    <!-- Custom CSS -->
    <link href="${contextRoot }/static/css/myapp.css" rel="stylesheet">

</head>

<body>


<div class="wrapper">

    <!-- Navigation -->
    <%@include file="share/navbar.jsp" %>

    <!-- Page Content -->
    <div class="content">
        <!-- Load only when user clicks Home -->
        <c:if test="${userClickHome == true }">
            <%@include file="home.jsp" %>
        </c:if>
        <!-- Load only when user clicks about -->
        <c:if test="${userClickAbout == true }">
            <%@include file="about.jsp" %>
        </c:if>
        <!-- Load only when user clicks contact -->
        <c:if test="${userClickContact == true }">
            <%@include file="contact.jsp" %>
        </c:if>

        <!-- Load only when user clicks all Products -->
        <c:if
                test="${userClickAllProducts == true or  userClickCategoryProducts == true}">
            <%@include file="listProducts.jsp" %>
        </c:if>


        <!-- Load only when user clicks show Products -->
        <c:if test="${userClickShowProduct == true }">
            <%@include file="singleProduct.jsp" %>
        </c:if>

        <!-- Load only when user clicks show Products -->
        <c:if test="${userClickManageProducts == true }">
            <%@include file="manageProduct.jsp" %>
        </c:if>

        <!-- Load only when user clicks show Cart -->
        <c:if test="${userClickShowCart == true }">
            <%@include file="cart.jsp" %>
        </c:if>


    </div>

    <!-- /.container -->

    <!-- Footer -->
    <%@include file="share/footer.jsp" %>

    <!-- jQuery -->
    <script src="${contextRoot }/static/js/jquery.js"></script>

    <!-- jQuery validator -->
    <script src="${contextRoot }/static/js/jquery.validate.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="${contextRoot }/static/js/bootstrap.min.js"></script>

    <!-- DataTable Plugin -->
    <script src="${contextRoot }/static/js/jquery.dataTables.js"></script>

    <!-- DataTable Bootstrap Script -->
    <script src="${contextRoot }/static/js/dataTables.bootstrap.js"></script>

    <!-- Boot Box  Script -->
    <script src="${contextRoot }/static/js/bootbox.min.js"></script>

    <!-- Self coded javascript -->
    <script src="${contextRoot }/static/js/myapp.js"></script>
</div>
</body>

</html>